# Generated by Django 4.2.2 on 2023-07-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('structure_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('idup', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('old', models.PositiveIntegerField(default=0)),
                ('orgid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guide.structure')),
            ],
        ),
    ]
